export const charData = [
  {
    value: "Bloodhound",
    id: 0,
    imageLink: require("./imgs/Bloodhound.png"),
    rDate: "2/04/2019",
  },
  {
    value: "Gibraltar",
    id: 1,
    imageLink: require("./imgs/Gibby.png"),
    rDate: "02/04/2019",
  },
  {
    value: "Lifeline",
    id: 2,
    imageLink: require("./imgs/Lifeline.png"),
    rDate: "02/04/2019",
  },
  {
    value: "Pathfinder",
    id: 3,
    imageLink: require("./imgs/Pathfinder.png"),
    rDate: "02/04/2019",
  },
  {
    value: "Wraith",
    id: 4,
    imageLink: require("./imgs/Wraith.png"),
    rDate: "02/04/2019",
  },
  {
    value: "Bangalore",
    id: 5,
    imageLink: require("./imgs/Bangalore.png"),
    rDate: "02/04/2019",
  },
  {
    value: "Caustic",
    id: 6,
    imageLink: require("./imgs/Caustic.png"),
    rDate: "02/04/2019",
  },
  {
    value: "Mirage",
    id: 7,
    imageLink: require("./imgs/Mirage.png"),
    rDate: "02/04/2019",
  },
  {
    value: "Octane",
    id: 8,
    imageLink: require("./imgs/Octane.png"),
    rDate: "03/19/2019",
  },
  {
    value: "Wattson",
    id: 9,
    imageLink: require("./imgs/Wattson.png"),
    rDate: "07/02/2019",
  },
  {
    value: "Crypto",
    id: 10,
    imageLink: require("./imgs/Crypto.png"),
    rDate: "10/01/2019",
  },
  {
    value: "Revenant",
    id: 11,
    imageLink: require("./imgs/Revenant.png"),
    rDate: "02/04/2020",
  },
  {
    value: "Loba",
    id: 12,
    imageLink: require("./imgs/Loba.png"),
    rDate: "05/12/2020",
  },
  {
    value: "Rampart",
    id: 13,
    imageLink: require("./imgs/Rampart.png"),
    rDate: "08/18/2020",
  },
  {
    value: "Horizon",
    id: 14,
    imageLink: require("./imgs/Horizon.png"),
    rDate: "11/04/2020",
  },
  {
    value: "Fuse",
    id: 15,
    imageLink: require("./imgs/Fuse.png"),
    rDate: "02/02/2021",
  },
  {
    value: "Valkyrie",
    id: 16,
    imageLink: require("./imgs/Valkyrie.png"),
    rDate: "03/04/2021",
  },
  {
    value: "Seer",
    id: 17,
    imageLink: require("./imgs/Seer.png"),
    rDate: "08/03/2021",
  },
  {
    value: "Ash",
    id: 18,
    imageLink: require("./imgs/Ash.png"),
    rDate: "11/02/2021",
  },
  {
    value: "Mad Maggie",
    id: 19,
    imageLink: require("./imgs/Maggie.png"),
    rDate: "02/08/2022",
  },
  {
    value: "Newcastle",
    id: 20,
    imageLink: require("./imgs/Newcastle.png"),
    rDate: "05/10/2022",
  },
  {
    value: "Vantage",
    id: 21,
    imageLink: require("./imgs/Vantage.png"),
    rDate: "08/09/2022",
  },
];
